plugins {
    id 'com.android.application'
}

android {
    namespace 'com.incomeoffers.app'

    compileSdk 35

    defaultConfig {
        applicationId 'com.incomeoffers.app'

        minSdk 23

        targetSdk 35

        versionCode 1

        versionName "1.0"
    }

    buildTypes {

        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    implementation 'androidx.webkit:webkit:1.12.1'
}
